# Generated by Django 3.2.4 on 2023-02-19 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_crosspointfield'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CrossPointField',
        ),
    ]
